<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Approval</name>
   <tag></tag>
   <elementGuidId>54f05f5a-d50a-42ad-a35a-e3c05677ed4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms-and-condition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;terms-and-condition&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
